// Generated by https://quicktype.io

export interface BankUser {
    usersData: UsersDatum[];
}

export interface UsersDatum {
    _id:                 string;
    package:             string;
    transactions:        string[];
    userId:              string;
    email:               string;
    totalBalance:        TotalBalance;
    billingInformation:  BillingInformation;
    transferInformation: TransferInformation;
    paymentStatus:       string;
    accountStatus:       string;
    createdAt:           string;
    updatedAt:           string;
    __v:                 number;
    assignedBankId:      string;
}

export interface BillingInformation {
    addressLine1:      string;
    addressLine2:      string;
    city:              string;
    district:          string;
    province:          string;
    zip:               string;
    country:           string;
    firstName:         string;
    lastName:          string;
    mobilePhoneNumber: string;
}

export interface TotalBalance {
    $numberDecimal: string;
}

export interface TransferInformation {
    address:           string;
    nearestLandmark:   string;
    lga:               string;
    state:             string;
    email:             string;
    zip:               string;
    country:           string;
    mobilePhoneNumber: string;
}
